apiVersion: v1
kind: Service
metadata:
  name: node-monitoring-service
spec:
  selector:
    app: node-monitoring-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
